# Generated by Django 4.1.6 on 2023-02-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dept_id',
            new_name='deptid',
        ),
    ]
